"""move tables to fnb schema

Revision ID: 09ade5ee110f
Revises: a2eda31eda13
Create Date: 2025-05-28 14:41:37.746187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09ade5ee110f'
down_revision: Union[str, None] = 'a2eda31eda13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    from alembic import op
    op.execute("CREATE SCHEMA IF NOT EXISTS fnb")
    # ... now drop indexes/tables in fnb ...
    op.drop_index(op.f('ix_fnb_entitlements_id'), table_name='entitlements', schema='fnb')
    op.drop_table('entitlements', schema='fnb')
    # ... etc ...
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
