"""Remove unwanted tables

Revision ID: 127c9c36e81d
Revises: 62b0c1b6b325
Create Date: 2025-05-28 00:41:20.482779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '127c9c36e81d'
down_revision: Union[str, None] = '62b0c1b6b325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
