"""move selected tables to fnb schema

Revision ID: d27e5407438e
Revises: 09ade5ee110f
Create Date: 2025-05-28 14:47:11.271166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd27e5407438e'
down_revision: Union[str, None] = '09ade5ee110f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS fnb")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('entitlement_type', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('registration_id', sa.Integer(), nullable=True),
    sa.Column('lunch', sa.Integer(), nullable=True),
    sa.Column('dinner', sa.Integer(), nullable=True),
    sa.Column('lunch_takenon', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dinner_takenon', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='fnb'
    )
    op.create_index(op.f('ix_fnb_audit_logs_id'), 'audit_logs', ['id'], unique=False, schema='fnb')
    op.create_table('food_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('is_vegetarian', sa.Boolean(), nullable=True),
    sa.Column('is_vegan', sa.Boolean(), nullable=True),
    sa.Column('is_gluten_free', sa.Boolean(), nullable=True),
    sa.Column('allergens', sa.String(), nullable=True),
    sa.Column('nutritional_info', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='fnb'
    )
    op.create_index(op.f('ix_fnb_food_data_category'), 'food_data', ['category'], unique=False, schema='fnb')
    op.create_index(op.f('ix_fnb_food_data_id'), 'food_data', ['id'], unique=False, schema='fnb')
    op.create_index(op.f('ix_fnb_food_data_name'), 'food_data', ['name'], unique=False, schema='fnb')
    op.create_table('registration_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('registration_fee', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='fnb'
    )
    op.create_index(op.f('ix_fnb_registration_types_id'), 'registration_types', ['id'], unique=False, schema='fnb')
    op.create_index(op.f('ix_fnb_registration_types_name'), 'registration_types', ['name'], unique=True, schema='fnb')
    op.create_table('entitlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('entitlement_type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='fnb'
    )
    op.create_index(op.f('ix_fnb_entitlements_entitlement_type'), 'entitlements', ['entitlement_type'], unique=False, schema='fnb')
    op.create_index(op.f('ix_fnb_entitlements_id'), 'entitlements', ['id'], unique=False, schema='fnb')
    # ### end Alembic commands ###

def downgrade() -> None:
    pass